### ISSUE TITLE
Jupyter/ Ipython Notebook Problem- SSL:Wrong Version Number

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#19]
Having a problem serving jupyter notebooks from the cluster.  Chris successfully did this on his system and it is unclear what has gone wrong for my personal anaconda install (python 2.7)

Followed instructions here as told 
http://jupyter-notebook.readthedocs.org/en/latest/public_server.html

many people have also had this issue recently

https://github.com/jupyter/notebook/issues/507

some have solved this by producing mycert.key and mycert.pem files and instead making them a single file called mycert.pem
(See below)
original: 
$sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mycert.key -out mycert.pem
my version: 
$sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mycert.pem -out mycert.pem

This does not work for me and I get this error continuously 

E 16:51:19.054 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)

**Comment by djakubosky** [comment]
Nevermind, Fixed this issue- requires https
